file_format: "1"
id: rolio
name: Rolio
type: shield
url: https://github.com/MickiusMousius/rolio
requires: [pro_micro]
features:
  - keys
  - encoder
  - backlight
siblings:
  - rolio_left
  - rolio_right
